### ISSUE TITLE
v0.1.9 net8.0 Requirement

### ISSUE THREAD

**Issue by Robertsmania** [Bukk94/KickLib#10]
I'm working on a project which is running as a plugin for VoiceAttack.  The framework requirements for that environment are strict, and it must be net7.0.

I've been running fine with KickLib v0.1.7 and would like to update to v0.1.9 but get this error from the package manager:
```
NU1202	Package KickLib 0.1.9 is not compatible with net7.0-windows7.0 (.NETCoreApp,Version=v7.0). Package KickLib 0.1.9 supports: net8.0 (.NETCoreApp,Version=v8.0)
```

Are there indeed aspects of v0.1.9 that require net8.0 or is it possible to adjust the library to work in net7.0?

**Comment by Bukk94** [comment]
Hi, 
main reason for switching to .NET 8.0 was no actual implementation requirement, but rather Microsoft support. .NET 7 support was officially ended in May 24th this year. For that reason I switched to .NET 8 which is LTS version. 
To allow you to still use KickLib even after EOS, I can try making KickLib multitarget, targeting both .NET 7 and 8.

**Comment by Bukk94** [comment]
@Robertsmania Alright, I think I made it :) KickLib version 0.1.10 should be supported on .NET 6, .NET 7, and .NET 8. Package manager should pull correct version for your needs :) Thanks for letting me know.

![image](https://github.com/Bukk94/KickLib/assets/3464841/b44d390b-b4a3-48eb-94ff-abcc4a0b2f56)

**Comment by Robertsmania** [comment]
Yes, that works. Thank you!
