### ISSUE TITLE
No longer firing _kickClient.OnMessage and can not post messages with SendMessageAsync()

### ISSUE THREAD

**Issue by Robertsmania** [Bukk94/KickLib#11]
My Kick client was working consistently, but today I find that its no longer handling the OnMessage event.  

The client is setup and connected like this:
```
        private static KickClient _kickClient = new KickClient();
        private static KickApi _kickApi = new KickApi();
...
                    var authSettings = new AuthenticationSettings(sekritLogin, sekritPW)
                    {
                        TwoFactorAuthCode = superSekritKey
                    };

                    _kickClient.ListenToChatRoomAsync(kickChannelID).GetAwaiter();
                    _kickClient.ConnectAsync().GetAwaiter();
                    _kickApi.AuthenticateAsync(authSettings).GetAwaiter();

                    _kickClient.OnMessage += HandleIncomingKickChatMessage;
```

But when users post messages in the chat, the HandleIncomingKickChatMessage method does not execute anymore.

If I try to post a message with this command:
```
                await _kickApi.Messages.SendMessageAsync(kickChannelID, messageContent);
```

We get this exception:
```
System.ArgumentException: Cannot send authenticated request without authenticating first! Call 'AuthenticateAsync' first.
   at KickLib.Clients.BrowserClient.SendAuthenticatedRequestAsync(String url, String payload)
   at KickLib.Core.BaseApi.PostAuthenticatedAsync(String urlPart, ApiVersion version, Object payload)
   at KickLib.Api.Messages.SendMessageAsync(Int32 chatroomId, String message)
   at RobertsmaniaStreaming.KickChat.SendKickChatMessage(String messageContent) in C:\Users\kris\source\repos\RobertsmaniaStreamingVAPlugin\StreamingVAPlugin\KickChat.cs:line 135
```

But there were no errors or exceptions when it initialized

**Comment by Robertsmania** [comment]
Yes, working again with 0.1.11

THANK YOU

**Comment by IhanaMies** [comment]
Doesn't seem to work anymore

**Comment by Bukk94** [comment]
> OnMessage event doesn't seem to work anymore

I just tested it and it works. `OnMessage` is being fired. Make sure you are using latest stable version (0.1.13) and before connecting the `KickClient`, you need to call `await client.ListenToChatRoomAsync(chatroomId)` with your `chatroomId`.
If you still have issues, open a new Issue and post your code, I'll try to help you :) 
@IhanaMies

**Comment by Bukk94** [comment]
> IhanaMies

It can be easily overlooked. I'm glad it's working! If you'll encounter any problems, feel free to reach out to me :)
