### ISSUE TITLE
StreamStateChangedArgs values are default

### ISSUE THREAD

**Issue by IhanaMies** [Bukk94/KickLib#13]
Version used: 0.1.13

KickClient.OnStreamStatusChanged event fires correctly when a stream comes online.
Values in StreamStateChangedArgs are however unusable as per pasted image.
Taking async from the signature of KickClient_OnStreamStatusChanged has no effect.

![image](https://github.com/user-attachments/assets/5602189d-6916-426e-bc42-5f594168956f)

I call Finalize() method in a static async CreateAsync() method which acts as an async constructor.
```csharp
private async Task Finalize()
{
	_kickClient.OnStreamStatusChanged += KickClient_OnStreamStatusChanged;

	Console.WriteLine($"Get channel info: {_channelName}");
	_channelInfo = await _kickApi.Channels.GetChannelInfoAsync(_channelName);

	await _kickClient.ListenToChannelAsync(_channelInfo.Id);
	Console.WriteLine($"Listening to channel: {_channelName}");

	await _kickClient.ListenToChatRoomAsync(_channelInfo.Chatroom.Id);
	Console.WriteLine($"Listening to chatroom: {_channelName}");
	await _kickClient.ConnectAsync();
}
```
Method called when stream status changes:

```csharp
private async void KickClient_OnStreamStatusChanged(object sender, KickLib.Client.Models.Args.StreamStateChangedArgs e)
{
	if (e.IsLive)
	{
		Console.WriteLine($"Live: {_channelInfo.Slug}");
		await StartRecording(DateTime.Now);
	}
	else
	{
		Console.WriteLine($"Live ended: {_channelInfo.Slug}");
		StopRecording();
	}
}
```

**Comment by Bukk94** [comment]
You are correct. I missed one nested data layer. I just published fixes. Try updating to version 0.1.14, data should be there. Thank you for reporting this.

**Comment by IhanaMies** [comment]
Thank you for fixing it.
