### ISSUE TITLE
Debug screenshot found in the nuget version of the library

### ISSUE THREAD

**Issue by ElGauchooooo** [Bukk94/KickLib#9]
I was having a hard time figuring this one out. It looks like you've published a different version to nuget than the one that is being listed here on github.

In `BrowserClient.SendRequestAsync(string url)` you have an `await page.ScreenshotAsync("D:/err.png")`. Could you please remove this one and  double check for other specialties, that are not being pushed to github? Thanks!

**Comment by ElGauchooooo** [comment]
![image](https://github.com/Bukk94/KickLib/assets/55155202/1dbea104-8f83-473e-9136-05027ef8fb52)

**Comment by ElGauchooooo** [comment]
Ah looks like you've removed it on 0.1.9.

**Comment by Bukk94** [comment]
Hi, this debug screenshot was included by mistake when package was compiled into new NuGet package and I didn't notice. Thanks for bringing that up. This code should be removed from 0.1.9.

I checked compiled package and version 0.1.9 doesn't contain any extra code. It matches master branch. In the future I would like to create CI/CD pipeline to release packages automatically without me needing to compile it myself.
